### ISSUE TITLE
All sorts of kernel panics with Toshiba EXCERIA 32GB SDHC on 0.6.31 build

### ISSUE THREAD

**Issue by Xnyle** [ayufan-rock64/linux-build#165]
I'm unable to boot using this card, kernel loads but then crashes at various points, doesn't get into systemd/init.

stretch-minimal-rock64-0.6.31-209-arm64.img.xz

Tested 4 identical cards, all unable to boot.

Other Samsung/Transcend non SDHC 16GB cards work fine.
Don't have another SDHC card available to test if it's a general SDHC issue.

Edit: found another Transcend 16GB SDHC card that's also not working.

Will try latest stable 0.5 and see if that's booting.

**Comment by Xnyle** [comment]
same problems on 0.5, mmcblk1: error -84 sending status command, aborting

**Comment by markh-de** [comment]
Same here. Got me an Exceria 64GB card, which I was planning to use as my root filesystem carrier. But same problem. I hope it's just a driver/configuration/clock issue of the Synopsys MMC IP core that can be solved in software.

**Comment by ayufan** [comment]
This is solved: https://github.com/ayufan-rock64/linux-build/releases/tag/0.6.40

**Comment by Xnyle** [comment]
This is not solved for me, still unable to use the mentioned card with 0.6.44, other cards work.
