### ISSUE TITLE
omv-firstaid option 1 not working

### ISSUE THREAD

**Issue by galosre** [ayufan-rock64/linux-build#306]
ERROR: dialog-like terminated due to an error: the dialog-like program exited with status 3 (which was passed to it as the DIALOG_ERROR environment variable). Sometimes, the reason is simply that dialog was given a height or width parameter that is too big for the terminal in use. Its output, with leading and trailing whitespace stripped, was:

Error: Expected at least 5 tokens for --menu, have 4.

**Comment by Zixim** [comment]
i've run into this just now also.
# omv-firstaid
select option 1 Configure network interface

results in : 
ERROR: dialog-like terminated due to an error: the dialog-like program exited with status 3 (which was passed to it as the DIALOG_ERROR environment variable). Sometimes, the reason is simply that dialog was given a height or width parameter that is too big for the terminal in use. Its output, with leading and trailing whitespace stripped, was:

Error: Expected at least 5 tokens for --menu, have 4.

**Comment by CityAstronaut** [comment]
I'm having the same error myself.

**Comment by Zixim** [comment]
this was fixed since the Feb 2 release.

**Comment by SeWittmann** [comment]
I still have this problem. I'm using 0.8.3: gitlab-ci-linux-build-141

Sebastian

**Comment by galosre** [comment]
I had to do a reinstall of stretch-openmediavault-rockpro64-0.7.9-1067-arm64.img
got the issue again

**Comment by baddinfinite** [comment]
got this issue as well.. Feb 2022. used newest version out. Was there ever a fix?
