### ISSUE TITLE
kernel build fails - fusb302

### ISSUE THREAD

**Issue by itdaniher** [ayufan-rock64/linux-build#66]
building https://github.com/ayufan-rock64/linux-kernel/commit/158f99435b56508b62ebb24ca7b52d673d1a7d08 

with 

> make rockchip_linux_defconfig
> make Image

fails with a host config of

```
rock64:~ $ uname -a
Linux rock64 4.4.77-rk3328 #29 SMP Mon Nov 20 03:26:28 CET 2017 aarch64 aarch64 aarch64 GNU/Linux
rock64:~ $ cat /etc/issue
Ubuntu 17.10 \n \l
```

yielding a traceback of

```
drivers/mfd/fusb302.c: In function ‘vdm_send_discoverysvid’:
drivers/mfd/fusb302.c:1164:3: warning: ‘memset’ used with length equal to number of elements without multiplication by element size [-Wmemset-elt-size]
error, forbidden warning: fusb302.c:1164
scripts/Makefile.build:258: recipe for target 'drivers/mfd/fusb302.o' failed
make[2]: *** [drivers/mfd/fusb302.o] Error 1
scripts/Makefile.build:403: recipe for target 'drivers/mfd' failed
make[1]: *** [drivers/mfd] Error 2
Makefile:986: recipe for target 'drivers' failed
make: *** [drivers] Error 2
```
any ideas? disabled this module, ran into another few issues. looking to get self-hosted kernel building on my rock64s.

Thanks!

**Comment by ayufan** [comment]
Fixed.

**Comment by itdaniher** [comment]
Still seeing this same error at 00f25666cb08d5bba0ecada39d0e820122238f22.
